name: newBlog deploy shell



on:

  push:

    branches: 

      - new



jobs:

  setup-build-publish-deploy:

    name: Setup, Build, Publish, and Deploy

    runs-on: ubuntu-latest

    steps:



    - name: Checkout

      uses: actions/checkout@v2

      with:

        persist-credentials: false

    - name: Install and build 🔧
      run: |
        yarn 
        yarn build
    
    - name: Deploy to Server 🚀
      users: easingthemes/ssh-deploy@v2.1.5
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        SOURCE: "build/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}