name: newBlog deploy shell



on:

  push:

    branches: 

      - new



jobs:

  setup-build-publish-deploy:

    name: Setup, Build, Publish, and Deploy

    runs-on: ubuntu-latest

    steps:



    - name: Checkout

      uses: actions/checkout@v2

      with:

        persist-credentials: false

    
    - name: Deploy to Server 🚀
      env: 
        DEMO: hi demo
      run: |
        echo $DEMO
        echo ${{ secrets.SSH_PRIVATE_KEY }}